<?php
$typeArr[11] = '企业简介';
$typeArr[10] = '联系我们';
$typeArr[12] = '招聘信息';
$typeArr[13] = '产品展示';
$typeArr[23] = '牧场系列';
$typeArr[15] = '钢桩系列';
$typeArr[16] = '宠物笼子系列';
$typeArr[17] = '临时栅栏系列';
$typeArr[22] = '电焊网系列';
$typeArr[19] = '配件系列';
$typeArr[20] = '其他系列';
$typeArr[21] = '塑料系列';
$typeArr[24] = '产品测试';
$typeArr[25] = '在线咨询';
$typeArr[26] = 'bbb';
$typeArr[27] = 'aaa';
$typeArr[28] = 'asd';
$typeArr[29] = 'aaaa';
?>