<li><a title="{dede:field name='typename'/}" href="{dede:field name='typeurl'/}">{dede:field
                            name='typename'/}</a>
                            <dl>
                                {dede:channel type='son' noself='yes'}
                                <dd><a title="[field:typename/]" href="[field:typeurl/]">[field:typename/]</a></dd>
                                {/dede:channel}
                            </dl>
                        </li>