<li><a href="[field:arcurl/]" title="[field:title/]">
                            <div width="294" height="219">
                                <img class="imgfra" src="[field:picname/]" alt="[field:title/]" />
                            </div>
                            <div class="acright">
                                <h4>[field:title/]</h4>
                                <p class="accon">　　[field:info/]...</p>
                            </div>
                        </a></li>