<li><a href="[field:arcurl/]" title="[field:title/]"><em></em><img class="newsimg" src="[field:picname/]" alt="[field:title/]" width="100" height="75" />
                            <div class="newsword">
                                <p class="top"><span>[field:title/]…</span>
                                    <label>[field:pubdate function="MyDate('Y/m/d',@me)"/]</label>
                                </p>
                                <div class="newscon">　　[field:info/]...</div>
                            </div>
                        </a></li>