<?php
$z[0]=Array("field","",87,116);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",168,197);
$z[1][4]['name']="typename";
$z[2]=Array("sql","\n                                    <li><a href=\"[field:typedir function='str_replace(\" {cmspath}\",\"\",@me)'/]\"\n                                        class=\"depth_3\">三级[field:typename/]</a></li>\n                                    ",313,644);
$z[2][4]['sql']="Select * from dede_arctype where reid=~id~ ORDER BY id limit 00,20";

?>