<a href='[field:arcurl/]'>[field:title/]</a>

                    <!--<ul class="slider-container">
                        <li class="item"> {dede:arclist typeid='13' titlelen='50' orderby='pubdate' }
                            <div class="limg">
                                <a class="img" href="[field:arcurl/]" title="[field:title/]"></a>
                                <a class="wor" href="[field:arcurl/]" title="[field:title/]">[field:title/]</a>
                            </div>