<div class="limg">
                                <a class="img" href="[field:arcurl/]" title="[field:title/]"></a>
                                <a class="wor" href="[field:arcurl/]" title="[field:title/]">[field:title/]</a>
                            </div>
                            {dede:channel type='top'}
                            <a href='[field:typelink /]'>[field:typename/]</a>
                            {/dede:channel}