<li><a href="[field:arcurl/]" title="[field:title/]">
                            <div class="imgborder">
                                <img class="imgfra" src="[field:picname/]" alt="[field:title/]" />
                            </div>
                            <div class="acright">
                                <h4>[field:title/]</h4>
                                <p class="accon">　　[field:info/]...</p>
                            </div>
                        </a></li>