<?php
$z[0]=Array("field","",27,55);
$z[0][4]['name']="typeurl";
$z[1]=Array("global","",62,86);
$z[1][4]['name']="itemindex";
$z[2]=Array("global","",126,150);
$z[2][4]['name']="itemindex";
$z[3]=Array("field","",154,183);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\n                <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>\n                ",249,394);
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>