<div class="limg">
                                <a class="img" href="[field:arcurl/]" title="[field:title/]"></a>
                                <a class="wor" href="[field:arcurl/]" title="[field:title/]">[field:title/]</a>
                            </div>
                            {dede:channel type='son' noself='yes'}
                            <dd><a title="[field:typename/]" href="[field:typeurl/]">[field:typename/]</a></dd>
                            {/dede:channel}