<?php
$z[0]=Array("flink"," [field:link /] ",135,211);
$z[0][4]['titlelen']="20";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("field","(@me==\"\")? @me=\" class='cur' \" :@me=\"\" ;}",418,510);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a>\r\n        </li>\r\n        ",583,880);
$z[2][4]['type']="top";
$z[2][4]['row']="10";
$z[2][4]['currentstyle']="<li> <a href='~typelink~' ~rel~ class='cur'><span>~typename~</span></a> </li>";
$z[3]=Array("global","",1063,1088);
$z[3][4]['name']="cfg_dizhi";
$z[4]=Array("global","",1110,1132);
$z[4][4]['name']="cfg_dh";
$z[5]=Array("global","",1242,1266);
$z[5][4]['name']="cfg_beian";
$z[6]=Array("global","",1268,1292);
$z[6][4]['name']="cfg_beian";
$z[7]=Array("type","\r\n    <a href=\"[field:typelink/]\" title=\"咨询\" class=\"barbook\"></a>\r\n    ",2640,2750);
$z[7][4]['typeid']="13";
$z[8]=Array("global","",2933,2959);
$z[8][4]['name']="cfg_webname";

?>