<?php
$z[0]=Array("global","",450,476);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",545,571);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",637,660);
$z[2][4]['name']="cfg_sjhm";
$z[3]=Array("channelartlist","\r\n    <li><a title=\"{dede:field name='typename'/}\" href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n      <dl>\r\n        {dede:channel type='son' noself='yes'}\r\n        <dd><a title=\"[field:typename/]\" href=\"[field:typeurl/]\">[field:typename/]</a></dd>\r\n        {/dede:channel}\r\n      </dl>\r\n    </li>\r\n    ",1857,2241);
$z[3][4]['typeid']="top";

?>