<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1045,1080);
$z[4][4]['filename']="head.htm";
$z[5]=Array("global","",1368,1393);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("channel"," <span><a href=\"[field:typeurl/]\" title=\"[field:typename/]\" class=\"\">[field:typename/]</a></span> ",1796,2000);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<span><a href='~typelink~'>~typename~</a></span>";
$z[7]=Array("list","\r\n      <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" width=\"220\" height=\"165\">\r\n        <p>[field:title/]</p>\r\n        </a></li>\r\n      ",2140,2370);
$z[7][4]['pagesize']="8";
$z[8]=Array("pagelist","",2461,2527);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2583,2620);
$z[9][4]['filename']="footer.htm";

?>