<li class="navlm"><a href='{dede:field name='typeurl'/}' id="a{dede:global.itemindex/}" class="li0  primary" onmouseover="Mea({dede:global.itemindex/});">{dede:field name='typename'/}</a>
              <div class="gdropdown list01">
                {dede:channel type='son' noself='yes'}
                <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>
                {/dede:channel}
              </div>
            </li>