<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,363);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",403,454);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1191,1226);
$z[4][4]['filename']="head.htm";
$z[5]=Array("global","",1514,1539);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("channel"," <span><a href=\"[field:typeurl/]\" title=\"[field:typename/]\" class=\"\">[field:typename/]</a></span> ",1942,2146);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<span><a href='~typelink~'>~typename~</a></span>";
$z[7]=Array("field","",2306,2325);
$z[7][4]['name']="title";
$z[8]=Array("field","",2399,2451);
$z[8][4]['name']="pubdate";
$z[8][4]['function']="MyDate('Y-m-d',@me)";
$z[9]=Array("field","",2504,2531);
$z[9][4]['name']="phpurl";
$z[10]=Array("field","",2555,2578);
$z[10][4]['name']="id";
$z[11]=Array("field","",2583,2607);
$z[11][4]['name']="mid";
$z[12]=Array("field","",3428,3446);
$z[12][4]['name']="body";
$z[13]=Array("prenext","",3603,3628);
$z[13][4]['get']="pre";
$z[14]=Array("prenext","",3629,3655);
$z[14][4]['get']="next";
$z[15]=Array("type"," <a href=\"[field:typelink/]\" title=\"返回列表\">返回列表</a>",3696,3785);
$z[16]=Array("include","",3868,3905);
$z[16][4]['filename']="footer.htm";

?>