<?php
$z[0]=Array("field","",270,289);
$z[0][4]['name']="title";
$z[1]=Array("global","",290,316);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",361,390);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",433,491);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1316,1351);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1688,1709);
$z[5][4]['name']="content";
$z[6]=Array("include","",3606,3643);
$z[6][4]['filename']="footer.htm";

?>