<?php
$z[0]=Array("global","",120,141);
$z[0][4]['name']="cfg_gg";
$z[1]=Array("global","",290,311);
$z[1][4]['name']="cfg_qq";
$z[2]=Array("global","",599,625);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",667,693);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("channelartlist","\n            <li class=\"navlm\"><a href='{dede:field name='typeurl'/}' id=\"a{dede:global.itemindex/}\" class=\"li0  primary\" onmouseover=\"Mea({dede:global.itemindex/});\">{dede:field name='typename'/}</a>\n              <div class=\"gdropdown list01\">\n                {dede:channel type='son' noself='yes'}\n                <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>\n                {/dede:channel}\n              </div>\n            </li>\n            ",919,1440);
$z[4][4]['row']="7";
$z[4][4]['typeid']="top";

?>