<?php
$z[0]=Array("global","",250,276);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",319,349);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",385,412);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1275,1310);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\n  <div class=\"ls-layer\"> <a href=\"#\"  class=\"ls-link\" target=\"_blank\"><img src=\"[field:litpic/]\" class=\"ls-bg\"  border=\"0\" /></a></div>\n  ",1467,1668);
$z[4][4]['row']="5";
$z[4][4]['titlelen']="36";
$z[4][4]['typeid']="1";
$z[5]=Array("channel","\n                <li class=\"i[field:global name=autoindex runphp=\"yes\"]@me=@me+1;[/field:global]\"> <a href='[field:typeurl /]'>\n                  <p class='add_iimg'></p>\n                  <p class='add_ititle'>[field:typename /]</p>\n                  </a> </li>\n                 ",2338,2669);
$z[5][4]['type']="son";
$z[5][4]['typeid']="8";
$z[6]=Array("arclist","\n      <dt><a href='[field:arcurl/]'><img src=\"[field:litpic/]\" width=\"187\" height=\"138\"></a></dt>\n      <dd><strong><a href='[field:arcurl/]'>[field:title/]</a></strong>\n        <p>[field:description function='cn_substr(@me,250)'/]...</p>\n      </dd>\n      ",2882,3206);
$z[6][4]['limit']="0,1";
$z[6][4]['titlelen']="36";
$z[6][4]['typeid']="4";
$z[7]=Array("arclist","\n      <li><a href='[field:arcurl/]'>[field:title/]</a></li>\n      ",3232,3365);
$z[7][4]['limit']="1,4";
$z[7][4]['titlelen']="44";
$z[7][4]['typeid']="4";
$z[8]=Array("channel","\n     <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\n    ",6833,6952);
$z[8][4]['type']="son";
$z[8][4]['typeid']="8";
$z[9]=Array("type","<a href=\"[field:typelink /]\" rel=\"nofollow\">查看更多</a>",6969,7063);
$z[9][4]['typeid']="8";
$z[10]=Array("arclist","\n    <li><img src=\"[field:litpic/]\" alt=\"[field:title/]\" border=\"0\">\n      <div class=\"project-content\">\n        <div class=\"inner-project\">\n          <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\n          <a href=\"[field:arcurl/]\" class=\"project-link\"  rel=\"nofollow\">更多</a></div>\n      </div>\n    </li>\n    ",7122,7506);
$z[10][4]['row']="4";
$z[10][4]['titlelen']="36";
$z[10][4]['typeid']="8";
$z[11]=Array("include","",7522,7557);
$z[11][4]['filename']="foot.htm";

?>