<?php
$z[0]=Array("field","",258,277);
$z[0][4]['name']="title";
$z[1]=Array("global","",278,304);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",347,376);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",418,476);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1075,1110);
$z[4][4]['filename']="head.htm";
$z[5]=Array("list","\r\n      <li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"><span class=\"fl\" style=\"font-weight:bold;color:#ff0000\">[field:title/]</span><span class=\"fr\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></a></li>\r\n      ",1379,1643);
$z[5][4]['pagesize']="6";
$z[6]=Array("pagelist","",1734,1800);
$z[6][4]['listitem']="index,end,pre,next,pageno";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",1855,1892);
$z[7][4]['filename']="footer.htm";

?>