<?php
$z[0]=Array("global","",264,290);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",331,360);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",400,458);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",1035,1070);
$z[3][4]['filename']="head.htm";
$z[4]=Array("list","\r\n      <li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"><span class=\"fl\" style=\"font-weight:bold;color:#ff0000\">[field:title/]</span><span class=\"fr\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></a></li>\r\n      ",1322,1587);
$z[4][4]['pagesize']="20";
$z[5]=Array("pagelist","",1678,1744);
$z[5][4]['listitem']="index,end,pre,next,pageno";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",1800,1837);
$z[6][4]['filename']="footer.htm";

?>